-- Insert sample plant diseases data
insert into public.plant_diseases (name, plant_type, description, symptoms, treatment, prevention) values
('Early Blight', 'Tomato', 'A fungal disease caused by Alternaria solani that affects tomato plants.', 'Dark spots with concentric rings on leaves, yellowing and wilting of lower leaves.', 'Apply fungicides containing chlorothalonil or copper. Remove affected leaves and improve air circulation.', 'Rotate crops, avoid overhead watering, and maintain proper plant spacing.'),
('Late Blight', 'Tomato', 'A serious fungal disease caused by Phytophthora infestans.', 'Water-soaked spots on leaves that turn brown, white fuzzy growth on leaf undersides.', 'Apply fungicides with metalaxyl or mancozeb. Remove infected plants immediately.', 'Use resistant varieties, avoid overhead irrigation, and ensure good drainage.'),
('Leaf Mold', 'Tomato', 'A fungal disease caused by Passalora fulva, common in greenhouse conditions.', 'Yellow spots on upper leaf surface, olive-green to brown fuzzy growth on undersides.', 'Improve ventilation, reduce humidity, apply fungicides if necessary.', 'Maintain proper spacing, avoid overhead watering, and use resistant varieties.'),
('Septoria Leaf Spot', 'Tomato', 'A fungal disease caused by Septoria lycopersici.', 'Small circular spots with dark borders and light centers, yellowing leaves.', 'Apply fungicides containing chlorothalonil. Remove affected foliage.', 'Mulch around plants, avoid overhead watering, and rotate crops.'),
('Bacterial Spot', 'Tomato', 'A bacterial disease caused by Xanthomonas species.', 'Small dark spots on leaves and fruit, yellowing and defoliation.', 'Apply copper-based bactericides. Remove infected plants.', 'Use pathogen-free seeds, avoid overhead irrigation, and practice crop rotation.'),
('Target Spot', 'Tomato', 'A fungal disease caused by Corynespora cassiicola.', 'Circular spots with concentric rings, similar to early blight but smaller.', 'Apply fungicides and improve air circulation.', 'Avoid overhead watering and maintain proper plant spacing.'),
('Mosaic Virus', 'Tomato', 'A viral disease that affects tomato plants.', 'Mottled yellow and green patterns on leaves, stunted growth.', 'No cure available. Remove infected plants to prevent spread.', 'Control aphids, use virus-free seeds, and practice good sanitation.'),
('Yellow Leaf Curl Virus', 'Tomato', 'A viral disease transmitted by whiteflies.', 'Yellowing and curling of leaves, stunted plant growth.', 'No cure available. Control whitefly populations.', 'Use reflective mulches, control whiteflies, and use resistant varieties.'),
('Early Blight', 'Potato', 'A fungal disease caused by Alternaria solani affecting potato plants.', 'Dark lesions on leaves with concentric rings, yellowing of foliage.', 'Apply fungicides and remove affected foliage.', 'Rotate crops and avoid overhead watering.'),
('Late Blight', 'Potato', 'A devastating disease caused by Phytophthora infestans.', 'Water-soaked lesions on leaves, white growth on undersides, tuber rot.', 'Apply fungicides immediately and destroy infected plants.', 'Use certified seed potatoes and ensure good drainage.'),
('Bacterial Spot', 'Pepper', 'A bacterial disease affecting pepper plants.', 'Small raised spots on leaves and fruit, yellowing and defoliation.', 'Apply copper-based sprays and remove infected plants.', 'Use pathogen-free seeds and avoid overhead irrigation.');
